export const ROUTE = {
	LANDING: '/',
	LANDING_SIGNUP: `/landing/signup`,
	LANDING_LOGIN: `/landing/login`,
	LANDING_FORGOT_PASSWORD: `/landing/forgot-password`,
	LANDING_RESET_PASSWORD: `/landing/reset-password`,
	USER_HOME: `/user/home`,
	USER_PROFILE: `/user/profile`,
	RESTAURANT_WISH_TABLE: `/restaurant-wish/table`,
	RESTAURANT_WISH_MAP: `/restaurant-wish/map`,
	RESTAURANT_FAVORITE_TABLE: `/restaurant-favorite/table`,
	RESTAURANT_FAVORITE_MAP: `/restaurant-favorite/map`,
	COOK_RECIPE_GRID: `/cook-recipe/grid`,
	COOK_RECIPE_TABLE: `/cook-recipe/table`,
	COOK_RECIPE_DETAIL: `/cook-recipe/detail`,
	COLLECTION_TABLE_GAME: `/collection/table/game`,
	COLLECTION_TABLE_SHOP: `/collection/table/shop`,
	COLLECTION_TABLE_STUDY: `/collection/table/study`,
}
